[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
via_ir = true
auto_detect_solc = false


remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@foundry-rs/=lib/foundry-rs/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
